name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run-job:
        description: "Run Specific Job"
        type: boolean
        required: false
      custom_message:
        type: string
        required: true
        description: "Enter a custom message"
      

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message 
        run: echo "Custom message - ${{ inputs.custom_message }}" 

      - name: Printing run-job boolean value
        if: ${{ inputs.run-job == true }}
        run: echo "run-job is ${{ inputs.run-job }}" 



# Append a new step to the already existing job2

# a. Add a single-step
#   i. Name: Printing run-job boolean value
#   ii. Execute an echo command to print the run-job input property of workflow_dispatch

# b. Make sure the step has an if condition with this expression - inputs.run-job == 'true' or inputs.run-job
#   i. This if condition makes sure that this step only executes when the run-job input parameter is checked/enabled